### PR TITLE
QR Code JWT Integration

### LINKED ISSUE #81: QR code: Make Result clickable to web browser if raw result is a valid URL
## Current Behaviour

Raw Result is displayed but not clickable if URL is valid

## Expected Behaviour

Add route to web browser if raw result is a valid URL

### LINKED ISSUE #127: Ability to read JWT token via QR Code
## Context

- Add scanning for QR Codes that contain JWT tokens
- Ability to decode and verify a signature
- Update display response
- Additional: Load JWT configuration as QR code in Settings screen

## Specs
- Scan QR code with JWT configuration
   - After scannig a QR code, it should redirect to the settings page
   - It will replace the current setting configuration `"Profile name"` and `"Public Key"`
   - A toast (popup info) information will show up saying `"Configuration loaded successfully"`
- Scan QR code with JWT payload
   - Must validate that the public key to decode JWT, otherwise it throws error saying `"Error: Signature verification failed. Please ensure a configuration profile was loaded"`
   - If success, it should show a list of key/values pair payload
   - If the button `"Show raw result"` is tapped, it will display the raw result page
- Scan QR code without JWT payload
   - It will show the raw result page
   
   

## Reference
Designs https://www.figma.com/file/olRF7LbcmADK0M3x3ytYNd/%5BSCOPE-174066%5D-ID-Pass-SmartScanner---Newlogic?node-id=0%3A1

Test Sample https://docs.google.com/document/d/12LAht16BKgov-7jSlvDktbZxoCG6g58cSIHz0lhaP4I/edit?usp=sharing

Test Sample 2 https://docs.google.com/document/d/1NWWSbEibXYEMnMleKP0LFKd3vlOACZM5xgJGJxTUNdA/edit?usp=sharing

### PR DESCRIPTION
**Pull request by rjmangubat23**
## Changes

1. Add JJWT library dependency
1. Refactor NON-ODK send result 
1. Initial Ability to Read JWT 

Fixes newlogic/smartscanner-core/issues/127
Fixes newlogic/smartscanner-core/issues/81

### CODE REVIEW

File: core-lib/src/main/java/org/idpass/smartscanner/lib/mrz/MRZAnalyzer.kt [hunk 1]
```diff
@@ -53,61 +56,104 @@ open class MRZAnalyzer(
...
+
                     val timeRequired = System.currentTimeMillis() - start
                     Log.d(
                         "${SmartScannerActivity.TAG}/SmartScanner",
                         "MRZ MLKit TextRecognition: success: $timeRequired ms"
                     )
                     var rawFullRead = ""
                     val blocks = visionText.textBlocks
+
+//                    val boxes = ArrayList<MRZBox>()
```
Comment (haklyray) [inline core-lib/src/main/java/org/idpass/smartscanner/lib/mrz/MRZAnalyzer.kt:133]: should these comments be deleted instead?

**Review by haklyray — APPROVED** [review]
there are some commented code that maybe should not be there/

File: core-lib/src/main/java/org/idpass/smartscanner/lib/mrz/MRZAnalyzer.kt (hunk 1 above)
Comment (nicholemnl) [reply core-lib/src/main/java/org/idpass/smartscanner/lib/mrz/MRZAnalyzer.kt:133]: Ahhh sorry, these will remain here for the meantime for the future debugging of MRZ.. Still getting feedback from other projects, so might be handy to have these here.

Will remove this once we have resolved the issue or improve the debugging condition here soon
